- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present


- name: load cities data
  ansible.builtin.shell: "mysql -h mysql-dev.hiteshshop.online -uroot -pRoboShop@1 < /app/schema/shipping.sql"